version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages:ro
      - ./components:/app/components:ro
    # env_file:
    #   - ./.env
